openapi: 3.0.0
info:
  title: Todo API with Auth
  version: 1.0.0
  description: API documentation for your Todo app with authentication
servers:
  - url: http://localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /api/user/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
      responses:
        "201":
          description: User registered
        "400":
          description: Bad request
  /api/user/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
        "400":
          description: Invalid credentials
  /api/todos:
    get:
      summary: Get all todos
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of todos
        "401":
          description: Unauthorized
  /api/todos/create:
    post:
      summary: Create a new todo
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                deadline:
                  type: string
                  format: date-time
      responses:
        "200":
          description: Todo created
        "401":
          description: Unauthorized
  /api/user:
    get:
      summary: Get user profile and todos
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User profile and todos
        "401":
          description: Unauthorized
